### ISSUE TITLE
CLP-S Slow Search with JSON Objects

### ISSUE THREAD

**Issue by Sheharyar-Khalid** [y-scope/clp#303]
### Bug

Hi,
 I am trying to compress and search some structured JSON data using CLP. I have around 1.6 TB of JSON data and CLP-s compresses it down to 44GB. The data looks something like this:
```
{

"Subject_uuid": "1EE9C4C4-4DEF-494E-A37D-32E64F33A81F", 

"Subject_type": "SUBJECT_THREAD", 

"Subject_cid": 3384, 

"Subject_parentSubject_UUID": "17561C13-D63B-4A47-874D-8BC65181CA9E", 

"Subject_localPrincipal": null, 

"Subject_startTimestampNanos": 1557234164075000000, 

"CDMVersion": "20", 

"type": "RECORD_SUBJECT", 

"hostId": "2AB88DCD-CBE6-41DF-AC69-9F6D6058E398", 

"sessionNumber": 4427, 

"source": "SOURCE_WINDOWS", 

"Subject_cmdLine_string": "\mozilla\firefox\firefox.exe",

"unix_timestamp": 1708885242.910084,

}
```

The issue is that my search takes a lot of time to complete. For example, for this query:

`'Subject_cmdLine_string: "*firefox.exe"'`

The CLP-S takes 4 minutes to search the compressed archives. I am trying to debug the issue and see the dictionaries. I found the `make-dictionaries-readable` function, but it does not work with clp-s.

Can you point me in the right direction so I can get the search time down to seconds?

Best,
Sheharyar

### CLP version

7745d0b

### Environment

Ubuntu 20.04.6 LTS

Compiled from source

### Reproduction steps

-

**Comment by kirkrodrigues** [comment]
Hi @Sheharyar-Khalid, apologies for the slow response.

`clp-s` currently searches with a single thread, so for your workload, it sounds like the thread would be searching the equivalent of 6.8 GB of uncompressed data per second. To quickly get better performance, you can try the CLP package which will distribute the work across multiple instances of `clp-s`.

We're still working on updating the docs for the package, but here's a brief guide to get started with it on a single node (with multiple cores):

* Build the package following the docs [here](https://github.com/y-scope/clp/blob/main/docs/Building.md).
* Inside the built package (build/clp-package), edit `etc/clp-config.yml`
  * Uncomment the lines "package" and "storage_engine"
  * Change `storage_engine: "clp"` to `storage_engine: "clp-s"`
* Start the package: `sbin/start-clp.sh`
* You can compress your logs using `sbin/compress.sh --timestamp-key unix_timestamp <logs-dir>`
  * To ensure maximum parallelism, you should try to split your input data into as many files as you have cores, or more.
* You can search your logs using `sbin/search.sh <kql-query>`
* When you're done, you can shut down the package using `sbin/stop-clp.sh`

Could you try that and let us know if it improves performance for your workload?

Regarding `make-dictionaries-readable`, we're working on a version that will work with `clp-s` archives.

**Comment by Sheharyar-Khalid** [comment]
Thanks for the detailed guide. 
This solves the issue and increases the speed.
