### ISSUE TITLE
clp-s: Support `?` to match single character in searches against variable value columns

### ISSUE THREAD

**Issue by gibber9809** [y-scope/clp#392]
### Request

Currently clp-s supports using wildcards to search against variable value columns, but not `?` to match a single character. Since this is supported on the log text search path the resulting behaviour is unintuitive.

### Possible implementation

The issue is that for this type of query we only enter into the wildcard search path if the predicate contains '*', ignoring `?` characters and escaping rules. We need to add some preprocessing along the variable value column search path to match the behaviour of the log text search path.

**Comment by wraymo** [comment]
Our log-text behaviour is to treat `?` as `*`, do we want the same thing?

**Comment by kirkrodrigues** [comment]
For clp-text/clp, that logic is a bit buggy (one issue is #243) but the intent was that we perform a wildcard match with the original query (including `?`) just after we decompress a message. For clp-json/clp-s, I would say we should treat `?` as matching any single character, as intended. We'll fix clp separately.
