### ISSUE TITLE
`network_reader_illegal_offset` unit test failure on macOS

### ISSUE THREAD

**Issue by kirkrodrigues** [y-scope/clp#519]
### Bug

The `network_reader_illegal_offset` unit test is failing on GH's macOS runners. The issue is being investigated and mitigated in #517.

### CLP version

1b67fdb

### Environment

Any macOS GH runner

### Reproduction steps

Run the clp-core-build-macos workflow on a macOS GH runner.

**Comment by LinZhihao-723** [comment]
The investigation shows that the issue only happens in some versions of `libcurl` on macOS, where HTTP return code 416 is not treated as `CURL_HTTP_RETURNED_ERROR`. In Ubuntu 20.04 and 22.04, we tried to update `libcurl` to 8.9.1 (which is the latest release when this comment was written) and it didn't reproduce.
Therefore, we suspect this is a macOS-specific issue and will handle it with specialized check for macOS only.
