### ISSUE TITLE
unable to get clp running in mac

### ISSUE THREAD

**Issue by tannaga** [y-scope/clp#79]
### Bug

I am trying to get clp up and running by following the instructions provided in https://github.com/y-scope/clp/blob/main/tools/packager/README.md but I see the below error `ModuleNotFoundError: No module named 'zstandard.backend_c'`

### CLP version

6d35126

### Environment

OS: MacOS Monterey
Python: 3.10.8
Docker version 20.10.17, build 100c701

### Reproduction steps

Steps:
1. Followed steps as per [building package](https://github.com/y-scope/clp/blob/main/tools/packager/README.md#building-the-package)
2. cd `out/clp-package-ubuntu-focal-x86_64-v0.0.1`
3. Start clp - `/sbin/start-clp --uncompressed-logs-dir <full path>`

**Comment by kirkrodrigues** [comment]
Hi @tannaga,

Sorry for the slow response. We're able to reproduce the bug and we'll push a fix soon. Thanks for reporting it!

**Comment by kirkrodrigues** [comment]
Hey @tannaga, when you get a chance can you pull, rebuild the package, and try again?

**Comment by tannaga** [comment]
@kirkrodrigues Thank you for the fix and quick turnaround. It is working now. I will continue to explore.
