### ISSUE TITLE
Compress command from Package-template gets stuck (process runs indefinitely)

### ISSUE THREAD

**Issue by thepegasos** [y-scope/clp#89]
### Bug

- When installed everything and ran the compress command via `pacakge-template/src/sbin`, it gives following output and hangs indefinitely. 
- The `../var` directory does have file sources BUT it never produces any archived files or directory
- Feel free to let me know if any other information is required
```
user@ubuntu1:~/code/CLP/clp/components/package-template/src/sbin$ ./compress /home/indra/TestLogs
2022-11-30 05:15:39,689 [INFO] [/opt/clp/sbin/native/compress] Compression job submitted to compression-job-handler.
2022-11-30 05:15:39,689 [INFO] [compression-job-handler] compression-job-handler started.
2022-11-30 05:15:39,695 [INFO] [job-1] Iterating and partitioning files into tasks.
2022-11-30 05:15:39,702 [INFO] [job-1] Waiting for 1 task(s) to finish.
```

Nothing after this. Here is the list of `/TestLogs` directory. 
```
user@ubuntu1:~/code/CLP/clp/components/package-template/src/sbin$ ls -l ~/TestLogs
total 12
-rw-rw-r-- 1 indra indra 4493 Nov 30 03:57 ibm_dummy_logs.log
-rw-rw-r-- 1 indra indra   70 Nov 30 02:01 my_log_file.log
```

### CLP version

0.0.1

### Environment

Ubuntu 20.04 LTS: 
```
user@ubuntu1:~/code/CLP/clp/components/package-template/src/sbin$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
user@ubuntu1:~ /code/CLP/clp/components/package-template/src/sbin$ docker -v
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
```

### Reproduction steps

- Installed `core` per the directions on the repository – directly on Ubuntu environment. Did not go with docker image route. 
- Installed packages `clp_py_utils`, `compression_job_handler`, and `job_orchestration` in `/components/package-template/src/lib/python3/site-packages/`
- Request: I want to build the "package" from scratch rather than playing with `package-template` and see if that works
- From the docs, I am unsure how to do that. Any pointers on doing that would help to troubleshoot this.

**Comment by thepegasos** [comment]
- Update: Built the package, followed instructions from [here](https://github.com/y-scope/clp/tree/main/tools/packager) and got it working. 
- There could be some intricacies regarding in-built template.
- Since it runs after making a package from scratch, closing this issue.
- If you face this or any similar issue with in-built package-template, build it from scratch by following instructions from [here](https://github.com/y-scope/clp/tree/main/tools/packager). Follow the docs!

**Comment by kirkrodrigues** [comment]
Glad you managed to get it working! Admittedly, we've been meaning to do a better job of documenting things, especially how to run the package without Docker. Hopefully we'll get to it some time in December.

**Comment by thepegasos** [comment]
- Sure, not a problem – clearly understandable. 
- Do let me know if you need a hand with that. As I just went through the end-to-end process, everything is super fresh in mind. Plus, through my opportunities in the MNCs, I have intensive experience in writing software along with technical documentation for end-users. 
- Would love to contribute and add value to the project as and when I can.
